apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
#      imagePullSecrets:
 #     - name: regcred3
      containers:
      - name: webapp1
        image: hello-world:latest
        ports:
        - containerPort: 80
          #      imagePullSecrets:
          #      - name: registry-creds
#      tolerations:
#        - key: "node-role.kubernetes.io/master"
#          effect: "NoSchedule"
#          operator: "Exists"
